version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # You can uncomment and set this if you have an API key
      # - VITE_GOOGLE_AI_STUDIO_KEY=${VITE_GOOGLE_AI_STUDIO_KEY}
    volumes:
      # Mount for development hot-reloading (optional)
      - ./src:/app/src
    restart: unless-stopped